;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	dired-show-file-type
	dired-unmark
	kill-region
	ns-copy-including-secondary
	org-kill-line
	org-self-insert-command
	sgml-slash
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	dired-previous-line
	end-of-buffer
	org-cycle-agenda-files
	))
